package com.coolhabit.textfieldgencompose.domain.entities

data class TextFieldSettings(
    var id: String,
    var align: String?,
    var backgroundColor: ColorRGB,
    var borderColor: ColorRGB,
    var borderWidth: Int,
    var bottomPadding: Int,
    var textColor: ColorRGB,
    var content: String,
    var placeholderText: String,
    var placeholderTextColor: ColorRGB,
    var executionDelay: Double?,
    var isFirstResponder: Boolean,
    var font: String?,
    var fontSize: Int,
    var isInput: Boolean,
    var isInputFieldHeightDynamic: Boolean,
    var keyboardType: String?,
    var leftPadding: Int,
    var lines: Int,
    var lineSpace: Int,
    var maxStroke: Int,
    var nextResponder: String?,
    var position: PositionXY,
    var cornerRadius: Int,
    var rightPadding: Int,
    var rimPadding: Int,
    var isScrollable: Boolean,
    var isSecureText: Boolean,
    var shadow: ShadowType,
    var size: SizeType,
    var underlineColor: ColorRGB,
    var underlineThickness: Int,
    var url: URLType?,
)
